### ISSUE TITLE
java jar built from current v23 is not working

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/base-starter-flow-osgi#206]
the current v23 branch is using **23.0.4**. 

running the following command:
- mvn install
- java -jar app/target/app.jar

then i can see the following errors

```
! Failed to start bundle com.example.osgi.base-1.0.0, exception Unable to resolve com.example.osgi.base [2](R 2.0): missing requirement [com.example.osgi.base [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component.page)(version>=23.0.0)(!(version>=24.0.0))) [caused by: Unable to resolve com.vaadin.flow.server [19](R 19.0): missing requirement [com.vaadin.flow.server [19](R 19.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=11.0.0))] Unresolved requirements: [[com.example.osgi.base [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component.page)(version>=23.0.0)(!(version>=24.0.0)))]
org.osgi.framework.BundleException: Unable to resolve com.example.osgi.base [2](R 2.0): missing requirement [com.example.osgi.base [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component.page)(version>=23.0.0)(!(version>=24.0.0))) [caused by: Unable to resolve com.vaadin.flow.server [19](R 19.0): missing requirement [com.vaadin.flow.server [19](R 19.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=11.0.0))] Unresolved requirements: [[com.example.osgi.base [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component.page)(version>=23.0.0)(!(version>=24.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:1007)
        at aQute.launcher.Launcher.start(Launcher.java:674)
        at aQute.launcher.Launcher.startBundles(Launcher.java:654)
        at aQute.launcher.Launcher.activate(Launcher.java:560)
        at aQute.launcher.Launcher.launch(Launcher.java:400)
        at aQute.launcher.Launcher.run(Launcher.java:181)
        at aQute.launcher.Launcher.main(Launcher.java:157)
        at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
        at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:119)
        at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```

**Comment by mcollovati** [comment]
Can't replicate locally on v23 branch. Works fine for me.

BTW we can maybe update pom.xml to set Java compiler source and target to 11

**Comment by ZheSun88** [comment]
@mcollovati i have checked with Tarek.. and this app doesn't work for neither of us. 

awww. 

i am having java 11.

**Comment by tarekoraby** [comment]
> BTW we can maybe update pom.xml to set Java compiler source and target to 11

Isn't this a must given that 23 only supports Java 11?

**Comment by ZheSun88** [comment]
issue got fixed. 
the problem is with the java path on a windows machine.
