### ISSUE TITLE
PiT 23.1: with Vaaidn 23.1, open the start UI throws errors

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/base-starter-flow-osgi#224]
### **step to reproduce:**

- checkout branch `update-v23.1` (or update the version and run mvn install)
- run `java -jar app/target/app.jar`

### **result:**

it throws error 
```
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.component.HasClearButton not found by com.vaadin.flow.server [19]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1585)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1352)
        at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1606)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1522)
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

```

**Comment by ZheSun88** [comment]
the `HasClearButton` is added in flow-component since V23.1. https://github.com/vaadin/flow-components/blob/23.1/vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/HasClearButton.java

checking the _MANIFEST_ of the `app.jar`, it looks the `vaadin-flow-components-base` jar has not been added to the bundle.
